# Generated by Django 3.1.7 on 2021-08-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledform', '0002_auto_20210806_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
