# Generated by Django 3.2.6 on 2021-08-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledform', '0004_alter_product_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='titre',
        ),
    ]
