# Generated by Django 3.2.6 on 2021-08-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledform', '0005_rename_title_product_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='summary',
            new_name='resume',
        ),
    ]
